[?1049h[?1l=[r12l[?1000l[?1002l[?1003l[?1005l[?1006l[?12l[?2004h[?1000h[?1002h[?1015h[?1006h[?1006l[?1015l[?1002l[?1000l[?1049l
[29;1HError occurred in server:

  [38;2;255;30;30mÃ—[0m Thread '[0;31mwasm[0;0m' panicked.
[38;2;255;30;30m  â”œâ”€â–¶ [0mOriginating Thread(s)
[38;2;255;30;30m  â”‚   [0m	[0;0m1. ipc_server: NewClient
[38;2;255;30;30m  â”‚   [0m	[0;0m2. pty_thread: NewTab
[38;2;255;30;30m  â”‚   [0m	[0;0m3. screen_thread: NewTab
[38;2;255;30;30m  â”‚   [0m	[0;0m4. plugin_thread: Update
[38;2;255;30;30m  â”‚   [0m
[38;2;255;30;30m  â”œâ”€â–¶ [0mAt src/wasm_vm.rs:145:42
[38;2;255;30;30m  â•°â”€â–¶ [0m[0;31mcalled `Result::unwrap()` on an `Err` value: RuntimeError { source: Trap(UnreachableCodeReached), wasm_trace: [FrameInfo { module_name: "<module>", func_index: 154, function_name: None,
[38;2;255;30;30m      [0mfunc_start: SourceLoc(91129), instr: SourceLoc(94366) }, FrameInfo { module_name: "<module>", func_index: 86, function_name: None, func_start: SourceLoc(50562), instr: SourceLoc(50791) },
[38;2;255;30;30m      [0mFrameInfo { module_name: "<module>", func_index: 68, function_name: None, func_start: SourceLoc(42221), instr: SourceLoc(42342) }, FrameInfo { module_name: "<module>", func_index: 343,
[38;2;255;30;30m      [0mfunction_name: None, func_start: SourceLoc(209940), instr: SourceLoc(231960) }], native_trace:    0: <unknown>
[38;2;255;30;30m      [0m   1: <unknown>
[38;2;255;30;30m      [0m   2: <unknown>
[38;2;255;30;30m      [0m   3: <unknown>
[38;2;255;30;30m      [0m   4: <unknown>
[38;2;255;30;30m      [0m   5: <unknown>
[38;2;255;30;30m      [0m   6: <unknown>
[38;2;255;30;30m      [0m   7: <unknown>
[38;2;255;30;30m      [0m }[0;0m
[38;2;255;30;30m      [0m   0: <zellij_utils::errors::Panic as core::fmt::Display>::fmt
[38;2;255;30;30m      [0m   1: miette::handlers::graphical::GraphicalReportHandler::render_causes
[38;2;255;30;30m      [0m   2: miette::handlers::graphical::GraphicalReportHandler::render_report
[38;2;255;30;30m      [0m   3: zellij_utils::errors::fmt_report
[38;2;255;30;30m      [0m   4: zellij_utils::errors::handle_panic
[38;2;255;30;30m      [0m   5: std::panicking::rust_panic_with_hook
[38;2;255;30;30m      [0m   6: std::panicking::begin_panic_handler::{{closure}}
[38;2;255;30;30m      [0m   7: std::sys_common::backtrace::__rust_end_short_backtrace
[38;2;255;30;30m      [0m   8: rust_begin_unwind
[38;2;255;30;30m      [0m   9: core::panicking::panic_fmt
[38;2;255;30;30m      [0m  10: core::result::unwrap_failed
[38;2;255;30;30m      [0m  11: zellij_server::wasm_vm::wasm_thread_main
[38;2;255;30;30m      [0m  12: std::sys_common::backtrace::__rust_begin_short_backtrace
[38;2;255;30;30m      [0m  13: core::ops::function::FnOnce::call_once{{vtable.shim}}
[38;2;255;30;30m      [0m  14: std::sys::unix::thread::Thread::new::thread_start
[38;2;255;30;30m      [0m  15: start_thread
[38;2;255;30;30m      [0m  16: clone
[38;2;255;30;30m      [0m
[38;2;106;159;181m  help: [0mIf you are seeing this message, it means that something went wrong.
        Please report this error to the github issue.
        (https://github.com/zellij-org/zellij/issues)
        
        Also, if you want to see the backtrace, you can set the `RUST_BACKTRACE` environment variable to `1`.
        
